### ISSUE TITLE
download is not working

### ISSUE THREAD

**Issue by xinnai** [congnv86/auto-download-facebook-emoji#1]
Hi, thank you for your work, I really want to get all the emoji from [https://emojipedia.org/facebook/4.0/](url) , but I don't know how. When I use your code I got the error bellow, can you help?
![Snip20210527_8](https://user-images.githubusercontent.com/23135336/119761246-0e7ca900-bede-11eb-85c6-2c71d97b6f6d.png)

**Comment by congnv86** [comment]
HI,
I've just test, and everything is OK. Maybe you missing this step:
```
npm install
```
